#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""
Jira List
"""

import configparser
import os
import sys
from jira import JIRA

if len(sys.argv) != 2:
    print("<jrcomments> JIRA-123")
    sys.exit(1)

config = configparser.ConfigParser()
config.read(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'config.ini'))
settings = config['config']
with open(settings['pass'], "r") as fp:
    password = fp.read().rstrip()

jira = JIRA(settings['host'], basic_auth=(settings['user'], password))
issue = jira.issue(sys.argv[1])
print("\n<description>")
print(issue.fields.description)
print("</description>\n")
for comment in issue.fields.comment.comments:
    print("\n<comment %s>" % comment.id)
    print(comment.body)
    print("</comment %s>\n" % comment.id)
