#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""
Jira List
"""

import configparser
import os
import sys
import subprocess
from jira import JIRA

if len(sys.argv) != 2:
    print("<jrcomments> JIRA-123")
    sys.exit(1)

config = configparser.ConfigParser()
config.read(
    os.path.join(
        os.path.dirname(os.path.realpath(__file__)),
        'config.ini'
    ))
settings = config['config']
with open(settings['pass'], "r") as fp:
    password = fp.read().rstrip()

jira = JIRA(settings['host'], basic_auth=(settings['user'], password))
issue = jira.issue(sys.argv[1])

import tempfile
with tempfile.NamedTemporaryFile(delete=True) as tmp:
    tmp.write(issue.fields.description.encode())
    tmp.flush()
    subprocess.run(["nvim", tmp.name])
    with open(tmp.name, "r") as tmpRead:
        issue.update(description=str(tmpRead.read()))
